#! /usr/bin/env bash

# @file        scripts/publish
# @author      Brandon Christie <bchristie.dev@gmail.com>

cd "${ dirname "$0"; }/.." || exit

function main()
{
    [[ -z ${ git status --porcelain; } ]] || exit

    local -r version=${ git describe --tags --abbrev=0; }

    go test -v ./... || exit

    GOPROXY=proxy.golang.org go list -m "github.com/BChristieDev/getopt_long.go@$version"
}

main "$@"
