#! /usr/bin/env bash

# @file        scripts/release
# @author      Brandon Christie <bchristie.dev@gmail.com>

cd "$(dirname "$0")/.." || exit

function main()
{
    [[ -z $(git status --porcelain) ]] || exit

    local -r opts=$(getopt -o "" -l "no-dry-run" -- "$@") || exit
    local dryRun=1
    local version=$(git describe --tags --abbrev=0)
    local semverType major minor patch tidy

    eval set -- "$opts"

    while true; do
        case "$1" in
            --no-dry-run) dryRun=; shift ;;
            --) shift; break ;;
            *) break ;;
        esac
    done

    semverType=${1?"Error: must specify semver type"}

    if [[ -z $dryRun ]]; then
        go test -v ./... || exit
    else
        echo "[DRY RUN]: would have run go tests"
    fi

    IFS=. read -r major minor patch <<<"${version:1}"

    case "$semverType" in
        major)
            ((major++))
            minor=0
            patch=0
            ;;
        minor)
            ((minor++))
            patch=0
            ;;
        patch)
            ((patch++))
            ;;
        *)
            echo "Error: $semverType is not a valid semver type" >&2
            exit 1
            ;;
    esac

    version="v$major.$minor.$patch"

    if [[ -z $dryRun ]]; then
        go mod tidy
        tidy=$(git status --porcelain go.mod)

        if [[ ${tidy[0]:1:2} == "M" ]]; then
            git add go.mod
            git commit -m "chore: tidy go.mod for version ${version:1}"
            git push
        fi
    else
        echo "[DRY RUN]: would have tidied go.mod"
    fi

    if [[ -z $dryRun ]]; then
        git tag -a "$version" -m "release: version ${version:1}"
        git push origin tag "$version"
    else
        echo "[DRY RUN]: would have created tag: $version"
    fi
}

main "$@"
