# @file        .github/workflows/ci.yml
# @author      Brandon Christie <bchristie.dev@gmail.com>

name: ci

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.23.x, 1.24.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go v${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        run: go test -v ./...
